language: python
python:
- '2.7'
services:
- docker
script:
- true
before_deploy:
- docker build -t sioworkers .
deploy:
- provider: script
  script: bash docker_push.sh
  on:
    branch: master
env:
  global:
  - secure: IC/tGorFP1bU/+2nQEmu5aGbYrP7dyN6uo/KsUwlMfZTCDjxBESxG2xgYD+nY4WZkEU6AjVutBdCGmBuyCpSkmbvFe3RKIYZmCLJakSDaFxft4ADZTJbhAM327KdoG7tTc9LhZHxcnNaQf8Pa0UhTv794b7xbWi89GvEOdEOC4hKQdLuEt1Hs/wOFy6oee3G4msM61i2HqB/93pcPP+IspUEqhcmxJuFMUhAVb3yWN9m+AKSo6cOy4qsO+8qiG00yCvq+udrXB2WsKDHgsVTreg+iuL15hxSDhgbD+71hgwPYuS3rkB3qdPbNYbXJcGc9W+kCborw0cxN5L/Ir1Jz99Y51yYbovc6gzd6Jnc1QtaQ1Bw1FWpVjgQ4aNb7T6bOz8wZwXfz5walLy+6hRsWz0914ZegKQJQrZipZJY1T+i+soq+XgpYsxytHvaEOd+LPBunUZlN7VSPeeJJxFPZwFJYDjqYrpz3rKTx6NL7NKBqx4Yg+VXQnSLF4zdQHnNAL5Ls8AgMxjs6F5XhMoZZxlHEdRBjM/JHD6BDZNnzdvwl86JrhbqroinLKV7sqJrVYhP7LV4xvfdiYuvUwowOQvN/O55WqAtnXlQiyy027qNA3Qle7keLdEj5GM92JM4IAYkVRddjIxi5sfbinOj2frU2IMHbwrBlxO+KiTARjQ=
  - secure: Xcs2M+81jLDYXp5kixIt9dPOQGqMchofTIkrA/Sw9qBnegbTE1yszz57qo2Ow3mO3TCG1KSPlYyYBdp4okK9VoeaMoitj8CQhp1UPTGdpfsNQADwBLkbPlv+zbrNTTvKDtwJ+bjjcr8O+AMwPHv1yPtuCZ1uyOItK+M/DnBW7aFp3COA+4PldojnHT5Hdk6aheSz5reH0UYnfEcCZwah3TkVtEsHyFxkedshTd7CK0RFyzmMI+2AjLzRiwvWPJ2X6x1r0xODY7V9U8dTg2QpKRfaWGELwl9Ri7h4p+Hg9liV8bS2wL26zqvy2zibaJJZi4mqVQMLkAK297Oxi3GAuPVKAVcqShwLoKeTpKgYNcFMxbQy+MLyOPMFfDtYZlFdKpnU2wqic+fDTE4dkZfwuehbkZHKt5II9DWHl+mZ8vIHobFuWqP+f12xCnFUxoMd8Sz5EW4K5zotpZiAVRpuHsX7KhpJVmry9a1vAGfZH4Dz2edwJU/ORHYLBj9us3IIoqZDJY301AwUAK1l0ayWzHrLqWOGoh0tfQ71c1lF618giih0oXAKTwE7mlaeJ9C1QVtGXY1vrPwvCvaMyYubSlAWGV2xjlSwRd2LgOiAzA8yMMhHlJ9T2WvP7absQgOerfDO4xs8ZiAfKJNpe8PTd8omHdlXttFfIftTiJZdukc=
